package enum_package;

public enum SessionKey {
	CURRENT_AUTH_TOKEN,
	CURRENT_USER_NAME,
	CURRENT_USER_ROLE,
	CURRENT_SCHOOL_ID,
	CURRENT_USER_ACCESSRIGHT,
	SUPER_AUTH_TOKEN,
	SUPER_USER_NAME,
	SUPER_USER_ROLE,
	SUPER_SCHOOL_ID,
	SUPER_USER_ACCESSRIGHT;
}
